### ISSUE TITLE
auk with custom ebird downloads - num columns and some names different

### ISSUE THREAD

**Issue by maniacalwhistle** [CornellLabofOrnithology/auk#11]
I was trying to use `auk` to read in an ebird custom data file: **ebd_US-NY-061_201701_201712_relNov-2017.txt (this is ebird data from Jan 2017 to Dec 2017 in NY)** but ran into this problem

` ebd <- auk_ebd("ebd_US-NY-061_201701_201712_relNov-2017.txt")`
`Error in auk_ebd("ebd_US-NY-061_201701_201712_relNov-2017.txt") : 
  Problem parsing header in EBD file.`

<img width="532" alt="parsing_prob_auk" src="https://user-images.githubusercontent.com/25876624/34961628-0fd53ada-fa0e-11e7-8a8f-28b6d4a35d4f.png">

Couldn't figure out what was going on, even after running auk_clean, so I compared the column headers of the sample file that comes with the auk package **"extdata/ebd-sample.txt"** and the file listed above. Turns out that the sample file has 46 columns and the custom file has 47 and there is mismatch on some of the column names (see attached image).

<img width="853" alt="head_exploration" src="https://user-images.githubusercontent.com/25876624/34961626-0d72e512-fa0e-11e7-8495-1c95bba18f7f.png">

I don't really have the memory to download the giant 24 gb file so I'd really like to get this to work. Also, if for some reason the headers are different in that file too (maybe there was an update?) then the problem would persist, right?

also, as an aside, can auk filter a sampling file in the same way it filters an ebd file, without loading in the ebd file? (using read_sampling only)

first time submitting an "issue" (maybe it isn't) so I hope I've provide enough information

**Comment by mstrimas** [comment]
Hi Michael,
Thanks for catching this! Coincidentally someone else sent me an email yesterday about the same issue. I've put through a temporary fix in the latest development version and will work on getting the custom downloaded files to have the same header as the full EBD, which will be a more permanent fix. Can you test to see if the dev version fixes the issue and let me know?

```
install.packages("devtools")
devtools::install_github("CornellLabofOrnithology/auk")
```

Also, there isn't currently a way to only filter the sampling file, but I think you could get around that by using a dummy EBD file:

```
library(auk)
dummy_ebd <- system.file("extdata/ebd-sample.txt", package = "auk")
sampling_f <- "sampling.txt"
sampling <- auk_ebd(dummy_ebd, file_sampling = sampling_f) %>% 
  auk_species(species = "Collared Kingfisher") %>% 
  auk_complete() %>% 
  auk_filter(file = "dummy_output.txt", file_sampling = "filtered_sample_file.txt") %>% 
  read_sampling()
```

**Comment by maniacalwhistle** [comment]
Thank you for the speedy reply, Matt.
I was able to read in the custom file using the fix you provided.

Excited to explore the data with `auk`.
