### ISSUE TITLE
countrycode new version breaks backward compatibility

### ISSUE THREAD

**Issue by vincentarelbundock** [CornellLabofOrnithology/auk#12]
Hi,

I am the maintainer of the `countrycode` package which you use as a dependency.

We're moving to version 1.00.0, and changing the name of the object where regexes and country codes are stored. Before, you had to look into the ``countrycode`` data.frame. Now it's called ``codelist``.

You'll probably want to add a line to check package version before digging right into that object.

This change is permanent; you can rest assured that countrycode will be a reliable dependency into the future.

Sorry for the trouble.

**Comment by vincentarelbundock** [comment]
http://github.com/vincentarelbundock/countrycode

**Comment by vincentarelbundock** [comment]
BTW, I recommend you keep loading regexes from my package directly instead of forking it, because we keep making improvements to the regexes. We also have a thorough test suite, etc.

**Comment by mstrimas** [comment]
Thanks for the heads up, I've modified the package to always use countrycode::countrycode() instead of the data frame.
