### ISSUE TITLE
unable to output to file with auk_filter

### ISSUE THREAD

**Issue by jsundahl** [CornellLabofOrnithology/auk#18]
I've been trying to do the example in the readme and am unable to get it to write to my output file. the code completes with no errors, but the output file has nothing in it. See code below:

```
input_file <- file.path("C:/path/to/ebd.txt")
output_file <- file.path("C:/path/to/out.txt")
ebd <- auk_ebd(input_file)
ebd_filters <- auk_species(ebd, species = "Gray Jay")
ebd_filters <- auk_country(ebd_filters, country = "Canada")
ebd_filtered <- auk_filter(ebd_filters, file = output_file, overwrite = TRUE)
```
I'm new to R, so let me know if I'm doing something that I shouldn't.

**Comment by mstrimas** [comment]
Sorry for the slow response, I've been on vacation.

What does `file.path("C:/path/to/ebd.txt")` point to? I can run the following example from the README without any trouble:

```
input_file <- system.file("extdata/ebd-sample.txt", package = "auk")
output_file <- "out.txt"
ebd <- auk_ebd(input_file)
ebd_filters <- auk_species(ebd, species = "Gray Jay")
ebd_filters <- auk_country(ebd_filters, country = "Canada")
ebd_filtered <- auk_filter(ebd_filters, file = output_file)
ebd_df <- read_ebd(ebd_filtered)
```

**Comment by jsundahl** [comment]
I ended up figuring out that the headers in the file I was using were wrong. I should have closed this issue, my apologies.
