### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by maelle** [CornellLabofOrnithology/auk#19]
# Not a bug report

:wave: @mstrimas! I've just tried making the code below (well an adaptation thereof)

```r
# ebd
f <- file.path(ebd_dir, "ebd_relMay-2018.txt")
f_clean <- file.path(ebd_dir, "ebd_relMay-2018_clean.txt")
auk_clean(f, f_out = f_clean, remove_text = TRUE)
# sampling
f_sampling <- file.path(ebd_dir, "ebd_sampling_relMay-2018.txt")
f_sampling_clean <- file.path(ebd_dir, "ebd_sampling_relMay-2018_clean.txt")
auk_clean(f, f_out = f_sampling_clean, remove_text = TRUE)
```

work on Windows and got no error but also no new file and then I realized I had the CRAN version, am now installing the dev version. 🤦‍♀️ I saw [this commit](https://github.com/CornellLabofOrnithology/auk/commit/ac01a2aba0e2ecc1faec188476860fdd4f76816f) and hope that was the reason why it didn't work? Anyhow I'll know tomorrow when I've run the code again.

# Actual question about Windows

Is there any reason why all `auk_clean` tests are skipped on Windows?

**Comment by maelle** [comment]
Reg the non-bug report, it works indeed now! (it was fast for the Germany-only file). But I still have my question about testing. 😉

**Comment by mstrimas** [comment]
Several of the key functions, e.g. `auk_clean(),  require the awk utility, which requires installing Cygwin on Windows, so I've skipped tests for these. If you're aware of a way to get around that I'd be keen to implement it. I keep missing Windows bugs because I don't have access to a Windows box.

**Comment by maelle** [comment]
My laptop is a Windows box at the moment then 😉

I yhink you can use cygwin on Appveyor with some config tweaking, https://www.appveyor.com/docs/build-environment/ I can look more into it next week.

**Comment by maelle** [comment]
What errors did you get when not skipping tests on Appveyor? I'm wondering whether Cygwin is installed by default.

**Comment by mstrimas** [comment]
oops, you're right, Cygwin is on Appveyor and the tests work 🤦 Will keep skip_on_cran() but remove skip_on_windows()
