### ISSUE TITLE
Small suggestion for auk_extent documentation

### ISSUE THREAD

**Issue by maelle** [CornellLabofOrnithology/auk#21]
I ran filtering of the German dataset, with a _bounding box_ using `auk_extent`. I was wondering whether you could add the words "bounding box" to `auk_extent` docs? That's the words I was actually looking for when reading the list of filters. So maybe "Filter the eBird data by spatial extent (bounding box)" as a function title and " spatial extent (bounding box) expressed" in the argument documentation?

**Comment by mstrimas** [comment]
Good point, changes made! Bounding box is probably a more standard term, do you think it would be worth changing the name of the function to `auk_bbox(x, bbox)`, then leaving `auk_extent(x, extent)` as an alias to eventually be deprecated?

**Comment by maelle** [comment]
Thanks!

Ah, good question! I *think* so but maybe you should ask for more opinions on rOpenSci's forum or slack (are you in there yet?)

**Comment by mstrimas** [comment]
You mean ask the community to see if extent or bbox would be a more intuitive name? Wasn't aware there was a forum or Slack, but I'll sign up for the forum and post something.

**Comment by maelle** [comment]
https://discuss.ropensci.org

And will invite you to the Slack in a minute.

You can also make a decision without asking anyone but I thought it'd be a good occasion for you to get plugged in.
