### ISSUE TITLE
auk_clean does not work

### ISSUE THREAD

**Issue by vjjan91** [CornellLabofOrnithology/auk#22]
I tried running auk_clean on the ebd as well as the sampling dataset, but it is simply producing an empty file in the directory mentioned. Any suggestions? 

I have also installed cygwin in the right folder.

**Comment by mstrimas** [comment]
First thing I always suggest is making sure auk is up to date with `devtools::install_github("CornellLabofOrnithology/auk")`. Next, check that `auk` is working on some of the included example files, e.g. look at the help for [`auk_filter()`](https://cornelllabofornithology.github.io/auk/reference/auk_filter.html) and see if those examples work. Finally, if that's working, send me the code you're running that isn't working.

**Comment by vjjan91** [comment]
Thanks, looks like the auk_filter and the others work, but clean did not work. That's fine though.
