### ISSUE TITLE
auk filter problem

### ISSUE THREAD

**Issue by ReedLab** [CornellLabofOrnithology/auk#28]
We are following the instructions for for filtering ebird data.  Our program worked fine on laptop, but too little RAM. moved to desktop, suddenly get an error message that it not found in the Googleverse

+   # 3. run filtering
+   auk_filter(file = f_out) %>% 
+   # 4. read text file into r data frame
+   read_ebd()
Error in auk_filter.auk_ebd(., file = f_out) : 
  auk_filter() requires a valid AWK install, unless execute = FALSE.

**Comment by mstrimas** [comment]
Can you provide a little more information about your system? Are you on Windows and, if so, do you have [Cygwin installed](https://cornelllabofornithology.github.io/auk/#installation)?

**Comment by ReedLab** [comment]
PC,  Windows 7
When I search the computer, I find Cygwin.h, and Cygwin.hpp  - is that sufficient?

**Comment by ReedLab** [comment]
Apparently I did not have Cygin installed, so I did that.  Now I’m waiting a few hours to see if it runs – it made it past the previous error statement, so that is excellent.  (my last fail was a memory problem – the computer I’m using has more RAM, so hopefully that will solve the problem).

Thanks for the prompt response,
Michael

**Comment by mstrimas** [comment]
Great, glad it's fixed! I thought that might be the issue. I'll close this issue, but feel free to re-open if you get another error.

**Comment by ReedLab** [comment]
Well, now it failed because it could not ‘allocate a vector of 47 mb’
It recommends I install the readr or data.table packages.  If I do this, do I then need to change my r code to used them, or will the program automatically use them?

Michael
