### ISSUE TITLE
Error in auk_ebd(.) : Required columns missing from the EBD file:

### ISSUE THREAD

**Issue by jasmyace** [CornellLabofOrnithology/auk#29]
Hello there, 

As the local neighborhood R-guy, I've been asked to read in a recent download of the big eBird dataset.  I'm having difficulty being successful.  I'm following the instructions [here](https://cornelllabofornithology.github.io/auk/articles/auk.html). 

I have run `devtools::install_github("CornellLabofOrnithology/auk")` and seem to be up-to-date: 
```r
Skipping install of 'auk' from a github remote, the SHA1 (b4ee8355) has not changed since last install.
  Use `force = TRUE` to force installation
```
I have unzipped the downloaded file, although I tried what follows on an original `.txt.gz` as well.  

I have downloaded and installed the Cygwin file `gawk.exe`, and I see it in `C:\cygwin64\bin`.

When I submit the following, 
```r
input_file <- "thefileishere/thefile.txt"      # or, /thefile.txt.gz
ebd <- input_file %>% 
  auk_ebd() 
```
I receive an error of 
```r
Error in auk_ebd(.) : Required columns missing from the EBD file:
	scientific name
	country code
	state code
	latitude
	longitude
	observation date
	time observations started
	protocol type
	duration minutes
	effort distance km
	all species reported
	sampling event identifier
	group identifier
```

When I dig into function `auk_ebd()`, I very quickly get to `utils.R` function `get_header`.  When I run this function, I get a row of data that doesn't look like typical "header" names at all:

![image](https://user-images.githubusercontent.com/9057972/54784565-d1277d00-4be9-11e9-9f59-2a90ed26854a.png)

I believe these are meant to be the column headers mentioned in the error.  

Have I done something wrong?  Is it possible that something happened with the download?   

I do note that when I dig into `auk_ebd()` in the same way, but with 
```r
file <-  system.file("extdata/ebd-sample.txt", package = "auk")
```
I see that object `header` returns with 
![image](https://user-images.githubusercontent.com/9057972/54785198-392a9300-4beb-11e9-8e9a-e9ba1a704aa8.png)

Thanks for any help you can provide.  

Here is `sessionInfo()`.  
![image](https://user-images.githubusercontent.com/9057972/54785359-aa6a4600-4beb-11e9-82f2-697590ce4b8b.png)

**Comment by mstrimas** [comment]
First, thanks for the detailed report! It makes it so much easier to answer questions when I have all the necessary info up front.

I think you must have a bad file here. Did you get the eBird Basic Dataset from here: https://ebird.org/data/download/ebd

**Comment by jasmyace** [comment]
I'm told that that is where we got it.

**Comment by mstrimas** [comment]
Hmm, that's odd, maybe it's an outdate file. The file should have the date in the name (e.g. `ebd_relDec-2018.txt`), what's your file called? Also, how big is it? Should be about 200 GB.

It looks like the file has no header. This shouldn't be the case, so I'm wondering if someone messed with it before sending it to you...

**Comment by jasmyace** [comment]
The original file I was asked to unzip is entitled `ebd_US_relJan-2019.txt.gz`.  The resulting unzipped file is entitled `ebd_US_relJan-2019.txt`.  Its final size, after unzipping, was 148,627,964 KB, or about 141 GB.

**Comment by jasmyace** [comment]
Did the download not complete?

**Comment by jasmyace** [comment]
My guy indicates that he thinks he limited it to the USA...but said he'll redownload it so he grabs all of it.  I'll let you know how it works out.

**Comment by mstrimas** [comment]
That's the right size for the US, 200 GB is for global

**Comment by mstrimas** [comment]
My suggestion is to start with the full/Global EBD, then do your filtering from that. I'm not sure what happened to the file you have, but there's something off and `auk` is primarily designed to work on the full EBD anyway. Use `auk_country("US")` to focus on the US records then apply whatever other filters you need to. Let me know if that works, if not we'll get it sorted out eventually!

**Comment by jasmyace** [comment]
It looks like after the full download it all ended up working.  

However, for what's it worth, my first attempt used the `dplyr` pipe sequence that includes function `auk_bbox`.  This returned an empty output text file (outside of column headers).  Using `auk_extent`, however, output what I expected.  

Thanks for the help.

**Comment by mstrimas** [comment]
That's great, glad to hear it's working?

I'm not sure why `auk_bbox()` wasn't working but `auk_extent()` is, particularly because `auk_extent()` is just a wrapper for `auk_bbox(), so the do exactly the same thing, i.e.:

```
auk_extent <- function (x, extent) {
    .Deprecated("auk_bbox")
    auk_bbox(x, bbox = extent)
}
```
