### ISSUE TITLE
AWK executable cannot be found

### ISSUE THREAD

**Issue by tanushrisundar** [CornellLabofOrnithology/auk#30]
I am using Windows 10 so I installed Cygwin. I am trying to run auk_filter and I get the following error message:  auk_filter() requires a valid AWK install, unless execute = FALSE

I checked the AWK_PATH which returns as NA. I tried to set the AWK_PATH to C:\cygwin64\bin\gawk.exe which has the following files (https://cdn1.imggmi.com/uploads/2019/6/25/e913a029e9d23965a8b985f1a3de51e3-full.png) but I get the error message: Specified AWK_PATH doesn't contain a valid AWK executable.

What am I missing? I open Cygwin.bat, run awk -W version, and see that AWK is installed. How come auk is unable to find the AWK executable?

**Comment by mstrimas** [comment]
It looks like you've installed Cygwin in the default location, so auk should be able to find it. Can you take a look at your .Renviron file (should be in your home directory) and let me know if there's a line for AWK_PATH? If so, what does is contain?

**Comment by tanushrisundar** [comment]
It turned out that auk was searching for the actual gawk executable, as opposed to the folder called "gawk.exe." When I set the AWK_PATH to C:\cygwin64\bin\gawk.exe\bin\gawk.exe, I was able to run the sample code provided on the auk installation site.

**Comment by mstrimas** [comment]
Glad it workout out!
