### ISSUE TITLE
Amount of data/no. of species in eBird?

### ISSUE THREAD

**Issue by sckott** [CornellLabofOrnithology/auk#32]
Hey there, as part of preparing an ropensci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to. 

Do you have a sense for how much data (e.g., in GB) one can access through ebird? How many species? How many observations?

thanks!

**Comment by mstrimas** [comment]
Roughly:
- 200 GB of data
- 10,000 species
- 700 million observations

**Comment by sckott** [comment]
thanks! that'll do it
