### ISSUE TITLE
read_ebd() fails to load auk_select() output

### ISSUE THREAD

**Issue by adokter** [CornellLabofOrnithology/auk#34]
After selecting a limited number of columns, in this case two:
```
out_file <- tempfile()
ebd <- auk_ebd(system.file("extdata/ebd-sample.txt", package = "auk"))
cols <- c("sampling event identifier", "observation count")
selected <- auk_select(ebd, select = cols, file = out_file, overwrite=T)
```
I can no longer read in the data with `read_edb()`:
```
> read_ebd(selected)
Error: `%in%`(x = group_id, table = names(x)) is not TRUE
```
It seems that read_edb() requires certain columns to be present in order to read the data succesfully, because adding more columns fixes the problem:
```
out_file <- tempfile()
ebd <- auk_ebd(system.file("extdata/ebd-sample.txt", package = "auk"))
cols <- c("group identifier", "sampling event identifier", 
          "scientific name", "observation count",
          "observer_id")
selected <- auk_select(ebd, select = cols, file = out_file, overwrite=T)
read_ebd(selected)
```
This example causes problems as well:
```
out_file <- tempfile()
ebd <- auk_ebd(system.file("extdata/ebd-sample.txt", package = "auk"))
cols <- c("group identifier", "sampling event identifier", 
          "observation count","observer_id")
selected <- auk_select(ebd, select = cols, file = out_file, overwrite=T)
```
Throwing a different error message:
```
> read_ebd(selected)
Error in get_message(lhs, call[[2]], env) : is.call(call) is not TRUE
```

**Comment by mstrimas** [comment]
Thanks for catching this! There are certain columns that need to be kept (group id, sampling event id, scientific name, and observation count) and I've made `auk_select()` now give an informative error message if you try to drop them. I've also added informative error messages to `auk_read()` if `group_identifier` or `scientific_name` are missing.

**Comment by Muzi04** [comment]
Hi Matt,

I am currently getting this same error. However, the presence file is read just fine but the checklists file throws this error. My auk, readr and data.table packages are all updated and my r version is 4.4.0. 

my_ebd_path = auk_get_ebd_path()# cos it's already set.

#_________Presence data
my_presence_file_loc <- paste0(my_ebd_path, "/ebd_US-FL_wiltur_201501_202312_smp_relMay-2024/ebd_US-FL_wilturPresence_201501_202312_May-2024.txt")
ebd_presence_data <- read_ebd(my_presence_file_loc)     #This works fine.

#_________Checklists data
   #*****First attempt
my_checklist_file_loc <-paste0(my_ebd_path, "/ebd_US-FL_wiltur_201501_202312_smp_relMay-2024/ebd_US-FL_wiltur_Allchecklists_201501_202312_May-2024_sampling.txt")
ebd_checklists_data <- read_ebd(my_checklist_file_loc)     #give same error as below.

#*****Second attempt
all_checklists <-  read_ebd(my_checklist_file_loc) %>%
  dplyr::select(sampling_event_identifier,locality_id, 
                latitude, longitude, observation_date, time_observations_started, 
                observer_id, protocol_type, duration_minutes, 
                effort_distance_km, effort_area_ha, number_observers, 
                group_identifier, scientific_name, exotic_code, country, state_code)

Error message: Error in get_message(lhs, call[[2]], env) : is.call(call) is not TRUE

**Comment by mstrimas** [comment]
Could you provide a link to download the file you're having trouble with?

```
ebd_US-FL_wiltur_Allchecklists_201501_202312_May-2024_sampling.txt
```

**Comment by Muzi04** [comment]
Please see the link below and let me know if you having trouble accessing it.

https://drive.google.com/file/d/1D8mlErYQckAlYMn1r4v41gOm5wcQuUcM/view?usp=drive_link

**Comment by mstrimas** [comment]
Oh, I see what's going on here: when you're reading in a checklist dataset (sampling event data) you should use `read_sampling()`. `read_ebd()` is only for reading in an observation dataset.

**Comment by Muzi04** [comment]
Yep, you are right. Thank you so much!
