### ISSUE TITLE
rnaturalearth and rnaturalearthhires packages won't install for RStudio desktop and RStudio cloud. 

### ISSUE THREAD

**Issue by aschuhmann** [CornellLabofOrnithology/auk#35]
* installing *source* package 'rnaturalearthhires' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : 
  there is no package called 'rnaturalearthhires'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'rnaturalearthhires'
* removing '\\cnhp2k/cnhp/Users/aschuhmann/My Documents/R/win-library/3.6/rnaturalearthhires'
Error in value[[3L]](cond) : 
  Failed to install the rnaturalearthhires package.
  Please try installing the package for yourself using the following command: 
     install.packages("rnaturalearthhires", repos = "http://packages.ropensci.org", type = "source")

**Comment by mstrimas** [comment]
How is this related to auk? Looks like the issue would be more appropriate for here: https://github.com/ropensci/rnaturalearthhires
