### ISSUE TITLE
filter_repeat_visits: closure for x number of days with multiyear data

### ISSUE THREAD

**Issue by roth-mh** [CornellLabofOrnithology/auk#36]
I am starting with data for a single species over many years.  I am hoping to create a repeat visit structure where populations are closed for part of the year (based on breeding season).

I see that filter_repeat_visits is designed to error out if _annual_closure_ = TRUE and _n_days_ is set.  Is there any reason for this in particular? are there considerations to make this feature available? I might be missing something.

**Comment by mstrimas** [comment]
n_days is meant to be used to group data in contiguous stretches of days, e.g. every 10 day period starting at date of the first observation. This could totally be done in such a way that the day counting resets each year, I just haven't implemented that yet. However, if I understand it correctly what you want in something different, e.g. to group say April 15 - June 30 of every year. If that's the goal, I suggest filtering your data to only those day ranges, then using `annual_closure = TRUE` and don't bother with the `n_days` argument at all.

**Comment by roth-mh** [comment]
Thank you for your speedy reply!

Oh nope, sorry for my lack of clarity -- the first interpretation is where my interest lies: **resetting the day counts each year**.  I am hoping to group April 15 - April 30 and June 1 - June 15 ... (for example) of each year. 

I have copied the source code for the _filter_repeat_visits_ function and plan to play with it a little bit this weekend. Do you have suggestions as to how to implement this? I am fairly new to R.

**Comment by mstrimas** [comment]
I pushed a quick change that should make this work, i.e. you can now specify `annual_closure = TRUE` and `n_days`. I haven't had time to test in detail, so if you're able to give it a try and report back I'd appreciate it. You'll need to install the GH version, this isn't on CRAN.

Note that there is the issue of alignment, i.e. when do you start the periods of closure. One option would be to start them at January 1st of every year, however, I've gone with using the earliest day of the year across all years. For example, if April 15th is the earliest date across all years of data, then counting will start from April 15th in every year.

**Comment by roth-mh** [comment]
Seems to work great! Only change I had to make was wrapping my integer inputs in a 'as.integer(x)' call.

Thanks a bunch!
