### ISSUE TITLE
auk_filter results in incomplete record list

### ISSUE THREAD

**Issue by JoseeRousseau** [CornellLabofOrnithology/auk#38]
I wish to do an auk_filter on the mega database "ebd_relApr-2020.txt" to download the records of 20 species.

I have used auk_filter in the past few months successfully (on a smaller ebd). Even now, I do not get any error messages. However, this time, the resulting file falls short of containing all the records it should have. It contains only 542 lines; see attachment: 
[ebd_spp1to20_Obs_20200608.txt](https://github.com/CornellLabofOrnithology/auk/files/4747507/ebd_spp1to20_Obs_20200608.txt)

Here is the script I used (I can provide the list of species if needed):
     ebd <- auk_ebd("D:/Data/eBird/ebd_relApr-2020/ebd_relApr-2020.txt") # external hard drive
     ebd_out_spp1to20 <- "D:/Data/eBird/MigrantNiche_Extracted_244spp/ebd_spp1to20_Obs_20200608.txt"
     ebd_filters <- ebd %>% 
	     auk_species(species = spp1) %>% 
	     auk_filter(file = ebd_out_spp1to20, overwrite = TRUE)

I have tried updating cygwin, updating auk (to version 0.4.1), restarting my computer, using different species but the resulting file is always incomplete.  Your guidance would be appreciated.

Thank you,

**Comment by mstrimas** [comment]
Sorry!! I thought I already responded to this, but clearly I was mistaken.

Is the issue still persisting? If so, it's unfortunately a tough one to troubleshoot. If you send me the list of 20 species, I could try running it myself and seeing what happens.

**Comment by JoseeRousseau** [comment]
I figured you were on vacation or something ....

Yes, this is still an issue that is persisting and for which I would love to find a solution.  I re-ran some codes today (I did not have the previous list of species saved). I have attached the files that were created with each run.  I will ultimately need to extract eBird records for 123 species.

    tier1spp <- c("Black-headed Grosbeak", "Black-throated Gray Warbler", "Cassin's Vireo", "Dusky Flycatcher", "Hammond's Flycatcher", "Hermit Warbler","Lazuli Bunting", "MacGillivray's Warbler", "Pacific-slope Flycatcher","Rufous Hummingbird", "Townsend's Warbler", "Virginia's Warbler","Western Kingbird", "Western Tanager", "Western Wood-Pewee")

    ebd <- auk_ebd("D:/Data/eBird/ebd_relApr-2020/ebd_relApr-2020.txt") # external hard drive
    ebd_tier1spp <- "D:/MigrationNiche/Data/MigrantNiche_Extracted_123spp/ebd_tier1spp_Obs_2005_2019_20200616.txt"
    ebd_filters <- ebd %>%
	    auk_species(species = tier1spp) %>%
	    auk_date(date = c("2005-01-01", "2019-12-31")) %>% 
	    auk_filter(file = ebd_tier1spp, overwrite = TRUE)

    ebd_tier1spp <- "D:/MigrationNiche/Data/MigrantNiche_Extracted_123spp/ebd_tier1spp_Obs_20200616.txt"
    ebd_filters <- ebd %>%
	    auk_species(species = tier1spp) %>%
	    auk_filter(file = ebd_tier1spp, overwrite = TRUE)

Thank you for helping out!

[ebd_tier1spp_Obs_2005_2019_20200616.txt](https://github.com/CornellLabofOrnithology/auk/files/4789107/ebd_tier1spp_Obs_2005_2019_20200616.txt)
[ebd_tier1spp_Obs_20200616.txt](https://github.com/CornellLabofOrnithology/auk/files/4789108/ebd_tier1spp_Obs_20200616.txt)

**Comment by mstrimas** [comment]
I don't have access to a Windows machine or the April EBD, but I ran this on a Linux box using the May 2020 and everything seems to work fine. I'm getting the following numbers of records for these two files:
4,621,887
5,453,913

Tough to troubleshoot what's going on for you. Probably worth at least getting the May 2020 EBD to ensure the issue isn't with the April file.

**Comment by JoseeRousseau** [comment]
Very good.  I'll download the May 2020 EBD and will let you know if things got solved (it will take me a couple of days to download).

Thanks for sharing the number of records for each file. That will be helpful.

**Comment by JoseeRousseau** [comment]
Downloading the May EBD and trying to unzip it was a good exercise.  It reminded me of the problems I had with the April EBD.  

In both cases, I was not able to unzip the EBD with 7zip. I got this error message "Data error: ebd_relMay-2020.txt.gz". 

I tried unzipping directly from cygwin, using this line "tar xvf ebd_relMay-2020.tar" and got this error message:
    ebd_relMay-2020.txt.gz
    tar: Unexpected EOF in archive
    tar: rmtlseek not stopped at a record boundary
    tar: Error is not recoverable: exiting now

I was able to unzip through R, using:
    gunzip(filename = "D:/Data/eBird/ebd_relMay-2020.tar", remove=FALSE,
		destname = "D:/Data/eBird/ebd_relMay-2020/ebd_relMay-2020.txt.gz")
This did not yield an error message, but the extracted May EBD file was smaller then it should be, i.e., the ebd_relMay-2020.txt.gz file was 96Gb instead of the expected 106Gb.  I now think problems unzipping the EBD could be the reason the auk codes did not work on the April EBD (I had unzipped the April EBD with through R, without checking sizes).

Do you have a recommendation about unzipping the EBD?

Any other solution to extract 123 species without using the mega EBD?  I could always request 123 species custom download EBD?  Not the best option, but I need to make progress.

Thanks,

**Comment by mstrimas** [comment]
This sounds frustrating! It sounds like a Windows issue, which I’m not very useful at troubleshooting since I use a Mac. Could you shoot me an email with the full species list mes335@cornell.edu
