### ISSUE TITLE
auk_zerofill error message when following "eBird Best Practices" Cornell doc

### ISSUE THREAD

**Issue by paulauvirage** [CornellLabofOrnithology/auk#39]
Hello

I am following the example for data import and creation of a zerofill data.frame in R 

in [2.3](https://cornelllabofornithology.github.io/ebird-best-practices/ebird.html) with code

```r
ebd_zf <- auk_zerofill(f_ebd, f_sampling, collapse = TRUE)`
```

and failing with the message

`Error: `%in%`(x = group_id, table = names(x)) is not TRUE`

I am using R 4.0.1 in R Studio 1.3.959 on Linux Ubuntu 20

Is this an auk error or a problem with the best practice doc working example?

Many thanks
Paul

**Comment by mstrimas** [comment]
What this error means is that there's no `group_identifier` column in either the EBD or SED file. Try importing the data with `read_ebd(f_ebd, unique = FALSE)` and see if the `group_identifier` field is there.
