### ISSUE TITLE
MODIS landcover data code question

### ISSUE THREAD

**Issue by ormaillet** [CornellLabofOrnithology/auk#40]
I'm going through the eBird Best Practices book and I have a question:
At the beginning of 3.2.2, it says "Note that at the time of writing, land cover data from 2019 haven’t been prepared yet, so we’ll use 2018 data for both 2018 and 2019."
```
# for 2018 use 2017 landcover data
  mutate(year_lc = if_else(as.integer(year) > max_lc_year, 
                           as.character(max_lc_year), year),
         year_lc = paste0("y", year_lc)) %>%
# (etc....)
```
I'm not sure if it's just not been updated or I'm reading it wrong, but should the code not say
```
# for 2019 use 2018 landcover data
```
?
 Anyway - what I would like to know is if I am using this MODIS landcover data set and only 2010-2018 ebird data, should I ignore this code/delete it when applying it to my project?

**Comment by mstrimas** [comment]
Oops, that's a typo, that's for catching it! Fixing it now. Yes, if you're only using data up to 2018, you can ignore that section.
