### ISSUE TITLE
Error: can't convert <double> to <list>

### ISSUE THREAD

**Issue by ormaillet** [CornellLabofOrnithology/auk#41]
I've run into an issue when trying to convert pland to the wide format. It had worked for me before while working with a single BCR (13) but now I have refiltered the dataset to include BCR 12 and 13 - could this be the issue?
This is the code I'm running before I get the error message: 
```
# tranform to wide format, filling in implicit missing values with 0s%>% 
pland <- pland %>% 
  pivot_wider(names_from = lc_name, 
              values_from = pland, 
              values_fill = list(pland = 0))
```
Then the error message:
```
Error: Can't convert <double> to <list>.
Run `rlang::last_error()` to see where the error occurred.
```
Then:
```
rlang::last_error()
```
 returned 
```
Error: Internal error: Trace data is not square.
Run `rlang::last_error()` to see where the error occurred.
rlang::last_error()
> #Trace data is not square
> rlang::last_error()
<error/rlang_error>
Internal error: Trace data is not square.
Backtrace:
  1. (function (x, ...) ...
  2. rlang:::print.rlang_error(x)
 10. rlang:::format.rlang_error(x, simplify = simplify, fields = fields)
 12. rlang:::format.rlang_trace(trace, ..., simplify = simplify)
 13. rlang:::trace_format_branch(x, max_frames, dir, srcrefs)
 14. rlang:::branch_uncollapse_pipe(trace)
Run `rlang::last_trace()` to see the full context.
```

Everything up until then had worked and given me the same "looking" list form "pland", ie:
1	2012	L294957	0.31034483	pland_00_water
2	2012	L1516757	0.32258065	pland_00_water
3	2012	L1498674	0.30000000	pland_00_water......

Thanks in advance! 

Olivia

**Comment by mstrimas** [comment]
Hi Olivia, this isn't an auk issue, would you mind posting over in the eBird Best Practices repo instead: https://github.com/CornellLabofOrnithology/ebird-best-practices/issues

**Comment by ormaillet** [comment]
Oops! Yes!
