### ISSUE TITLE
auk_split not exporting data

### ISSUE THREAD

**Issue by iknayank** [CornellLabofOrnithology/auk#44]
auk_split is creating per species files with headers, but not writing out any records. Function returns the value "2".

I believe the issue is that this line of code:
```
  exit_code <- system2(awk_path, args = paste0("'", awk, "' ", file), 
                       stderr = FALSE)
```
should be
```
  exit_code <- system2(awk_path, 
                       args = paste0("'", awk, "' '", file, "'"),
                       stderr = FALSE)
```

**Comment by mstrimas** [comment]
Seems to be working for me, can you try running the example in `?auk_split`, if that works but your code isn't there may be an issue with your input files. If the example isn't working, can you share the output from `sessionInfo()`. Thanks!

**Comment by auman-chan** [comment]
I met this problem as well. This function only exported files without any rows. Only I splited species before filter would it work.
![image](https://github.com/CornellLabofOrnithology/auk/assets/89596802/cf2223d8-9555-434a-a44d-fbec5a14ba40)

**Comment by mstrimas** [comment]
Can you provide the output of `sessionInfo()` and the code that generated the above output?
