### ISSUE TITLE
read_ebd -> Error: length(readLines(x, 2)) not greater than 1

### ISSUE THREAD

**Issue by sofbol94** [CornellLabofOrnithology/auk#47]
hello,
I'm trying to extract ebird data from a polygon, every time i use bbox() i get thie error with read_ebd(). Any help? i already updated auk to the most recent version.
here is the code:

````
f_in <- "data/ebd_B_poly.txt"
auk_ebd("/Users/sofia/Desktop/ebd_sensitive_relMar-2020.txt") %>% 
  auk_bbox(polyB) %>% 
  auk_date(c("2000-01-01", "2020-01-01")) %>% 
  auk_complete() %>% 
  auk_filter(f_in)

ebdB <- read_ebd("data/ebd_B_poly.txt")
Errore: length(readLines(x, 2)) not greater than 1
````
thanks, 
sofia

**Comment by mstrimas** [comment]
auk cannot filter to a polygon, auk_bbox only works with min and max latitude and longitude provided. you should first us auk_bbox to filter to a bounding box around the polygon, then read the data into R and further filter to the polygon using the sf package.
