### ISSUE TITLE
auk_version() up to date?

### ISSUE THREAD

**Issue by nmtarr** [CornellLabofOrnithology/auk#49]
Hi.  I had version 0.4.2 of Auk installed with RStudio for some work last year.  I recently acquired a new copy of the EBD and updated my Auk version to 0.4.3.  However, when I run "auk_version()" I get the following:

$auk_version
[1] "auk 0.4.2"

$ebd_version
[1] "2019-08-15"

$taxonomy_version
[1] 2019

I have tried removing and reinstalling several times and the problem persists.  One consequence is that I get the following warning when I run "read_ebd()":

_Warning message:
In auk_species.auk_ebd(., species = species) :
  Based on the EBD filename, it appears you should use taxonomy_version = 2020_

Apologies in advance if this is the result of an error on my part.

Nathan Tarr

**Comment by mstrimas** [comment]
Hi Nathan,

You can safely ignore that warning. There was no taxonomy update this past
year, so auk 0.4.3 will work just fine with the most recent EBD.

Matt

**Comment by nmtarr** [comment]
Excellent.  Thank you.
