### ISSUE TITLE
auk requires taxonomy_version = 2020 which does not exist

### ISSUE THREAD

**Issue by rachbergmann** [CornellLabofOrnithology/auk#52]
I have just downloaded auk and R. Using OSX 10.14.6.  

When I try to retrieve data from a downloaded ebird txt file I get

```
Warning` message:
In auk_species.auk_ebd(., species = c("American Robin")) :
  Based on the EBD filename, it appears you should use taxonomy_version = 2020
```

But that taxonomy_version does not exist. 

How do I force the taxonomy version I do have or get a new version.

```
> auk_version()
$auk_version
[1] "auk 0.4.2"

$ebd_version
[1] "2019-08-15"

$taxonomy_version
[1] 2019
```
```
> ebd_filtered <- "/Users/rachelle/ebirdData/ebd_US-NM-017_relFeb-2021/ebd_US-NM-017_relFeb-2021.txt" %>%
+ auk_ebd() %>%
+ auk_species(species = c("American Robin")) %>% 
+ auk_filter(file = output_file)
Warning message:
In auk_species.auk_ebd(., species = c("American Robin")) :
  Based on the EBD filename, it appears you should use taxonomy_version = 2020
> get_ebird_taxonomy() 
Error in loadNamespace(name) : there is no package called ‘readr’
```
And after the filtering, the output_file is returned but contains only the header from the original file
```
GLOBAL	UNIQUE	IDENTIFIER	LAST EDITED DATE	TAXONOMIC ORDER	...
```

("American Robin") is just an example. I have tried scientific names, other bird names, and have looked at Clements-Checklist-v2019-August-2019.xlsx

**Comment by rachbergmann** [comment]
OK. So of course just after turning in this report, I found a code path that works, and the warning is just that, a warning. The output file contains the American Robin observations.
```
>  ebird_data <- f_in %>%
+ auk_ebd() %>% 
+ auk_species(species = "American Robin") %>% 
+ auk_filter(file = f_out) %>%
+ read_ebd()
Warning messages:
1: In auk_species.auk_ebd(., species = "American Robin") :
  Based on the EBD filename, it appears you should use taxonomy_version = 2020
2: In choose_reader(reader) :
  read.delim is slow for large EBD files, for better performance install the readr or data.table packages.
>
```
where f_in is the input file from above and f_out is defined with f_out <- filename

That means there is something wrong with the code I was originally using. Though I am still not quite sure what that is, because the function structure I show in my original report is taken from an example. Though I couldn't tell you exactly where I got that. There are lots of examples, and different function structure in function definitions and various online examples.

**Comment by mstrimas** [comment]
Looks like you solved your problem, but you can safely ignore that warning. For a variety of reasons, there was no 2020 taxonomy update, so the 2019 taxonomy will work just fine.

As far as I can tell, the two bits of code you posted are essentially identical, so I'm not sure what's going on there. When that sort of stuff happens, my usual advice is to restart your R session, start with a totally blank slate, and try again.
