### ISSUE TITLE
Ebird example R script and data file

### ISSUE THREAD

**Issue by PRFisher-git** [CornellLabofOrnithology/auk#54]
The AUK starter files from eBird do not appear to be up to date.  Auk package refers to a data example file from 2018 and Canadian example, whereas the download includes a 2021 data example and US species?
When I run the script the error says 'Based on the EBD filename, it appears you should use taxonomy_version = 2020' and 'there's no package called 'pillar'....  I tried installing pillar though no fun; tried both examples provided and included spp from the data example.

can someone provide R script that works for beginners + matching data example?? Thanks

setwd("C:/Users/Paul Fisher/Documents/R/R Input/eBird")
install.packages("pillar")
library(pillar)
library(auk)
library(dplyr)
# path to the ebird data file, here a sample included in the package
# in practice, provide path to ebd, e.g. input_file <- "data/ebd_relFeb-2018.txt"
input_file <- "ebd_US-AL-101_202103_202103_relMar-2021.txt"
# output text file
output_file <- "ebd_filtered_grja.txt"
#ebird_data <- input_file %>% 
# 1. reference file
  #auk_ebd() %>% 
  #auk_species(species = "Blue Jay") %>%
  auk_country(country = "United States") %>% 
  # 3. run filtering
  #auk_filter(file = output_file) %>% 
  # 4. read text file into r data frame
  #read_ebd()

input_file <- "ebd_US-AL-101_202103_202103_relMar-2021.txt"
#  output_file <- "ebd_filtered_grja.txt"
ebd <- auk_ebd(input_file)
ebd_filters <- auk_species(ebd, species = "Blue Jay")
ebd_filters <- auk_country(ebd_filters, country = "United States")
ebd_filtered <- auk_filter(ebd_filters, file = output_file)
ebd_df <- read_ebd(ebd_filtered)

**Comment by lime-n** [comment]
This should get you up and running:

```
library(tidyverse)
library(auk)

input_file <- "ebd_US-AL-101_202103_202103_relMar-2021.txt"
ebd <- auk_ebd(input_file)

ebd_filter <- ebd %>%
  auk_species(species = "Blue Jay") %>%
  auk_country(country = "United States") %>%
  auk_filter(file = "testfile.txt")

output_file <- "testfile.txt"

read_ebd("testfile.txt")
```

**Comment by PRFisher-git** [comment]
Thanks looking at it again, I think part of the issue was using dplyr
rather than tidyverse.
Rgds
Paul
