### ISSUE TITLE
Add progress bars

### ISSUE THREAD

**Issue by trashbirdecology** [CornellLabofOrnithology/auk#60]
Suggest adding progress bar to `read_ebd()` and `auk_zerofill()` to give estimate of time or percent remaining. 

If working with AWK isn't too hard, I may try to submit a PR at some point, but perhaps someone can get to this sooner.

**Comment by mstrimas** [comment]
The `read_` functions are wrappers around `readr::read_tsv()`, which itself has a `progress` argument defaulting to `readr::show_progress()`. My understanding from reading the help for `show_progress` is that a progress bar will typically be shown when the read functions are called interactively, which is I think the behaviour we want here. I have noticed that reading is so far that for most files I never see the progress bar, but if I try to read a file with a few million lines it does show up. Let me know if this is what you were looking for with this issue.

**Comment by trashbirdecology** [comment]
Off the top of my head, I think that for some reason vroom::read_X (which is what readr::read_X uses I think) stops showing progress after readLines hits something like 2.15GiB.

**Comment by mstrimas** [comment]
I don't see anything like that here: https://www.rdocumentation.org/packages/vroom/versions/1.0.2/topics/vroom_progress

When I read the full Sampling Event Data file (18+ GB) I do see a progress bar like:

```
indexing ebd_sampling_relAug-2021.txt [==============================-----------] 1.49GB/s, eta: 10s
```

I think this is behaving the way we want, so I'm going to close this for now. Feel free to re-open if there's something different you think this progress bar should be doing.

**Comment by mstrimas** [comment]
Right, I've noticed that as well, but I think it probably makes sense since these smaller files get read in extremely quickly so even when I force the progress bar to appear it appears and disappears in a blink. Most of the time in the read functions is typically spent de-duping shared checklists and rolling up sub-species, and for these things there's no simple way to show a progress bar.
