### ISSUE TITLE
Reference to max count in auk-unique comments

### ISSUE THREAD

**Issue by nmtarr** [CornellLabofOrnithology/auk#63]
I was looking through [auk-unique()](https://github.com/CornellLabofOrnithology/auk/blob/main/R/auk-unique.r) in order to better understand how group checklists are handled with read_ebd() and I saw reference to "max count" and "max number of birds" in the comments.  I may be reading the code wrong, but it doesn't look like individual counts are actually used in this code.  Is that correct or am I missing something?  Are those comments outdated?

**Comment by mstrimas** [comment]
Thanks for catching that, the documentation is outdated, for simplicity it now just grabs the count from the first submitted checklists. I need to update the docs.

**Comment by nmtarr** [comment]
OK.  No worries, and thanks for checking for me.
