### ISSUE TITLE
Get a species list from ebird file

### ISSUE THREAD

**Issue by jivelasquezt** [CornellLabofOrnithology/auk#64]
Is there a way to use auk to extract only unique species names (common or scientific) from an eBird file without having to load the full file to memory? I mean, a more elegant way to do this:

```
f_in <- "/Users/jorge/Documents/Data/eBird/ebd_CO_relDec-2021/ebd_CO_relDec-2021.txt"

ebird_data <- f_in %>% 
  auk_ebd() %>% 
  auk_filter(file = "tmp.txt", overwrite=T) %>% 
  read_ebd()

sp_list <- unique(ebird_data$scientific_name)
```

**Comment by nmanich** [comment]
If you are looking for all the unique species in a region you can download that (bottom right) from the bar chart:
https://ebird.org/barchart?r=CO&yr=all&m=

**Comment by mstrimas** [comment]
There used to be a really nice public API for programmatically getting that bar chart data, but unfortunately it no longer exists 😞 Nick's solution will do the job though.

If you specifically want the species list from a EBD file, no there isn't a direct way to do this in `auk`. However, for a state level file like you have above, you probably can just read into R and subset unless your computer has limited memory. If that isn't an option, note that `readr` has a `col_select` argument that allows you to only read in certain columns. For example, you could do something like:

```
library(readr)
library(dplyr)
library(auk)

read_tsv(f_in, col_select = "SCIENTIFIC NAME") %>% 
  count(scientific_name = `SCIENTIFIC NAME`) %>% 
  inner_join(ebird_taxonomy, ., by = "scientific_name") %>% 
  arrange(desc(n))
```

This will give you the number of records for each taxa in that EBD file and uses a lot less memory than reading the whole EBD.

**Comment by jivelasquezt** [comment]
The second solution works best for my purpose. I want to know what species are in a file without having to load the entire file to memory which may be an issue with large files (or having to know beforehand what state or country the file is from),  Thanks!
