### ISSUE TITLE
Error while using read_ebd function

### ISSUE THREAD

**Issue by igloopigloo** [CornellLabofOrnithology/auk#66]
Hi,

I am trying to use read_ebd() as shown exactly in best practices. But I keep getting error:
**Error in readr::read_delim(x, delim = sep, quote = "", na = "", col_types = col_types,  : 
  unused arguments (col_select = which(header != ""), name_repair = "minimal")**

My code is exact copy of workshop and looks like this
`ebd_filtered <- auk_ebd("ebd_2014-2015_yucatan.txt") %>% 
  auk_species("Yellow-rumped Warbler") %>% 
  auk_country("GT") %>% 
  auk_protocol(c("Traveling", "Stationary")) %>% 
  auk_complete() %>% 
  auk_filter(file = "data/ebd_yerwar.txt")

ebd <- read_ebd("data/ebd_yerwar.txt", unique = FALSE, rollup = FALSE)
`

Any help would be really appreciated.

Thanks.

**Comment by mstrimas** [comment]
Can you let me know which version of `readr` you have with `packageVersion("readr")`? I'm guessing that you need to update that package.

**Comment by igloopigloo** [comment]
Hi Matt,

Yes that was readr issue and it is working now! And thank you so much.

But now auk_zerofill() is not working. The following statement
`ebd_zf <- auk_zerofill(f_ebd, f_sampling, collapse = TRUE)`

is giving me following error:
**Error in get_message(lhs, call[[2]], env) : is.call(call) is not TRUE**

Can you please help me with this.

Thanks.

**Comment by mstrimas** [comment]
It's hard to tell what's going on from that error. Are you able to run the simple example in the documentation for `?auk::auk_zerofill`:

```
library(auk)
f_ebd <- system.file("extdata/zerofill-ex_ebd.txt", package = "auk")
f_smpl <- system.file("extdata/zerofill-ex_sampling.txt", package = "auk")
ebd_df <- auk_zerofill(x = f_ebd, sampling_events = f_smpl, collapse = TRUE)
```

**Comment by btojenniferborder** [comment]
Hi, 

I'm having the same issue with the read_ebd function:

Error in readr::read_delim(x, delim = sep, quote = "", na = "", col_types = col_types, :
unused arguments (col_select = which(header != ""), name_repair = "minimal")

I'm using readr version 1.4.0. I've tried updating but this seems to be the most recent version I get and I still get the error. 

Thanks,
Jenni

**Comment by igloopigloo** [comment]
> Hi,
> 
> I'm having the same issue with the read_ebd function:
> 
> Error in readr::read_delim(x, delim = sep, quote = "", na = "", col_types = col_types, : unused arguments (col_select = which(header != ""), name_repair = "minimal")
> 
> I'm using readr version 1.4.0. I've tried updating but this seems to be the most recent version I get and I still get the error.
> 
> Thanks, Jenni

Hi Jenni,

I updated my packages and everything seems to work fine. Hope this helps.

Thanks

**Comment by btojenniferborder** [comment]
Thanks both. I think it's the version of R I'm using, 3.6.3. I'll get this updated and see if that helps :-)

**Comment by igloopigloo** [comment]
> It's hard to tell what's going on from that error. Are you able to run the simple example in the documentation for `?auk::auk_zerofill`:
> 
> ```
> library(auk)
> f_ebd <- system.file("extdata/zerofill-ex_ebd.txt", package = "auk")
> f_smpl <- system.file("extdata/zerofill-ex_sampling.txt", package = "auk")
> ebd_df <- auk_zerofill(x = f_ebd, sampling_events = f_smpl, collapse = TRUE)
> ```

Hi Matt,

One more question, I can't install dggridR to create hexagonal grids. The package is not on CRAN anymore, even devtool does not work for this. Is there any other way around this.

Thanks,

**Comment by mstrimas** [comment]
Oh no! I'll have to remove that from the book. Uber has an open source library for working with hexagonal grids, I haven't explored it much myself, but there is an R package for it here: https://github.com/crazycapivara/h3-r/

Alternatively, you could use a plain old square grid, e.g. with the raster or terra package.

**Comment by igloopigloo** [comment]
Yeah found the first one and was also thinking about the second option.

Thanks Matt.

**Comment by mstrimas** [comment]
Hexagonal grids do have some nice properties that make them good for this sort of use, but it's not going to make a huge difference. If it's going to be easier to use a square/raster grid, I would go for it!
