### ISSUE TITLE
Incomplete checklists error despite `auk_complete()` in filter definition

### ISSUE THREAD

**Issue by dhduncan** [CornellLabofOrnithology/auk#67]
I am trying to construct some P/A datsets from the Australia-only download of the May 2022 release, paired with the May 2022 pre-packaged sampling effort file.  When I try to `auk_zerofill` the filtered object I get an error saying that there are some incomplete checklists and suggesting that I should include `auk_complete()` in the filter definition.  

That condition _is_ already in my filters definition, and I feel like I am following the guidance, so am I inadvertently tripping something?

Filter definition
```
filters <- auk_ebd(f_in, 
                   file_sampling = f_sampling) %>%
  auk_bbox(bbox = c(112.5, -44.5, 154.5, -9.5)) %>%  # this should be redundant but I wondered if there was a spatial mismatch prob
  auk_species(species = "Phalacrocorax fuscescens") %>% 
  auk_year(year = c(2021, 2022)) %>% 
  auk_complete() 
```
Filter definition is confirmed below:
```
> filters
Filters
  Species: Phalacrocorax fuscescens
  Countries: all
  States: all
  Counties: all
  BCRs: all
  Bounding box: Lon 112.5 - 154.5; Lat -44.5 - -9.5
  Years: 2021, 2022
  Date: all
  Start time: all
  Last edited date: all
  Protocol: all
  Project code: all
  Duration: all
  Distance travelled: all
  Records with breeding codes only: no
  Complete checklists only: yes
```
I apply the filter, which takes an age to process (as promised)
```
> test_pa_filtered <- auk_filter(filters,
                               file = paste0(out_path, "birds/P_fuscescens_pa_filtered.txt"),
                               file_sampling = paste0(out_path, "birds/sampling_pa_filtered.txt"), overwrite = TRUE
                               )
```
but then the zerofill operation fails immediately
```
> df_zf <- auk_zerofill(test_pa_filtered, collapse = TRUE)
 **0s Error in auk_zerofill.data.frame(x = ebd, sampling_events = sed, species = species,  :                        
  Some checklists in sampling event data are not complete.
Complete checklists are required for zero-filling.
Try calling auk_complete() when filtering.**
```
It seems that error message is true, as the output sampling file does have checklists where completeness was not asserted:
```
read_sampling(paste0(out_path, "birds/sampling_pa_filtered.txt")) %>% 
group_by(all_species_reported) %>% 
count()
# A tibble: 2 × 2                                                                   
 0s# Groups:   all_species_reported [2]
  all_species_reported     n
  <lgl>                <int>
1 FALSE                    2
2 TRUE                     1
```
Any pointers gratefully accepted.

**Comment by dhduncan** [comment]
One detail that might or might not be important... When I unpack the sampling event `.tar` object the data file appears as an 7.2 GB `.txt.gz` archive within the main archive total (7.3 GB). If I try to unzip that it suggests that the contained item is a .txt file of around 220 MB, which seems highly unlikely.  I never get to find out because it can't be unarchived. I just changed the extension to `.txt` presuming it was incorrect...
![Screenshot from 2022-06-23 12-07-59](https://user-images.githubusercontent.com/5265962/175192055-e16588fc-73a0-40b8-bf8c-17a4817ca1a8.png)

**Comment by mstrimas** [comment]
I don't think I understand what you've done with the `.txt.gz` file. Are you saying you didn't unzip this file, you just renamed `.txt.gz` to `.txt`? That shouldn't work because auk requires the uncompressed text file, which is not what you have. The strange thing is, you seem to have successfully produced the file ` birds/sampling_pa_filtered.txt` from this compressed text file.

Do you have external drive you could unzip that file too? auk will work with files on an external hard drive.

I would also start by immediately filtering the sampling event file to just Australia so it matches your EBD file. You can use `auk_sampling()` for this. Then, you can work with the matching EBD and sampling event data for the remaining filtering.

**Comment by dhduncan** [comment]
Thanks, I'll report back.

**Comment by dhduncan** [comment]
Thanks @mstrimas for your response, which has helped me resolve the problem.  I don't know if it is worth trying to justify how I got myself in that pickle, but yes, so odd that a filtered sampling file was able to be produced (at least on my linux machine).

> I would also start by immediately filtering the sampling event file to just Australia so it matches your EBD file.

I had wondered about this, but then I presumed that by referencing the sampling file in the `auk_ebd()` call where the filters were defined that the result would be a commonly filtered dataset.

**Comment by mstrimas** [comment]
Thanks for the feedback, I think you're right about the need for clarifying how to filter when you've downloaded a subset of the EBD. Most of this content was written back in the days when the EBD was a manageable size, so downloading the whole thing wasn't a big deal. Those days are gone, so I really need to update `auk` to make it more clear how the workflow works when using EBD subsets downloaded through the custom download form.
