### ISSUE TITLE
Different records in TXT file and Data Frame

### ISSUE THREAD

**Issue by lgooch2845** [CornellLabofOrnithology/auk#68]
I'm new to Auk. I'm not sure that what I've found is a bug, but it is unexpected.

I'm using a download of data for Cuyahoga County, Ohio, from 2000 to 2021. I've filtered that for observations within a bound box, and I got a seemingly satisfactory result of about 25,000 records. Code follows. What is unexpected is that the filtered output text file (Ebird_OutputData.txt) has 24,556 observations, while the filtered data frame (ebird_data) has 21,489. 

I looked at the two versions of the data to try to sort out the source of this behavior. To a first approximation, it seems that the data frame filters out duplicate records that are part of a group (that is, shared checklists only show up once) and records that are in a Category other than "species." There may be some other records filtered out, but these account for the majority of the records "missing" from the data frame. For my filtered data, that resulted in a difference of 3067 observations.

To be clear, the smaller number of records appears both in the data frame (as shown if I run str(ebird_data) and in the written CSV file (Filtered_Ebird.csv).

As I said, I'm not sure that this is exactly a bug, but I would expect the data frame and the TXT file to include the same data.

Thanks for your consideration.

Code:

```
input_data <- "C:/.../ebd_US-OH-035_200001_202112_relJun-2022.txt"

# Define the path for the output text file.

output_data <- here("OutputData", "Ebird_OutputData.txt")

# Filter the data using the Auk package.

ebird_data <- input_data %>% 
  auk_ebd() %>% # This command sets up a reference to the dataset file that is used in filtering.
  auk_bbox(bbox = c(lng_min=-81.565047, lat_min=41.480931, lng_max=-81.553851, lat_max=41.484628)) %>% # This defines a filter to extract only the data                                                                                                          # inside a lat/long box.
  auk_filter(file = output_data, overwrite=TRUE) %>% # This applies the filter or filters defined above.
  read_ebd() # This reads the filtered data into the ebird_data dataframe.

write_csv(ebird_data, here("OutputData","FilteredEbird.csv"))
```

**Comment by mstrimas** [comment]
The two things you've noticed are likely what's causing the difference: collapsing grouped checklists and accounting for non-species taxa. This section from the eBird Best Practices book has more details: https://cornelllabofornithology.github.io/ebird-best-practices/ebird.html#ebird-zf

If you want to turn off these features, use `read_ebd(collapse = FALSE, rollup = FALSE)`

**Comment by lgooch2845** [comment]
Matt,
Thank you. I had not gotten as far as reading the best practices docs, which I should probably have done before my post.
Laura

    On Friday, August 5, 2022 at 10:53:30 PM EDT, Matt Strimas-Mackey ***@***.***> wrote:  
 
 


The two things you've noticed are likely what's causing the difference: collapsing grouped checklists and accounting for non-species taxa. This section from the eBird Best Practices book has more details: https://cornelllabofornithology.github.io/ebird-best-practices/ebird.html#ebird-zf

If you want to turn off these features, use read_ebd(collapse = FALSE, rollup = FALSE)
