### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [CornellLabofOrnithology/auk#69]
Some topics are missing from the configuration file.

```r
Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: auk, valid_protocols
```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by mstrimas** [comment]
Thanks for catching this, should be fixed now
