### ISSUE TITLE
Bug: Code implicitly expects `R_ENVIRON_USER` is not set

### ISSUE THREAD

**Issue by aidan-gibson** [CornellLabofOrnithology/auk#77]
`auk-set-ebd-path.R` writes to `~/.Renviron`
A user could have `R_ENVIRON_USER` set for a custom `.Renviron` that this is ignoring.

However, what the code should really do is use a project-level `.Renviron`

**Comment by aidan-gibson** [comment]
(similar steps should be taken for `auk-set-awk-path.R`)

**Comment by mstrimas** [comment]
Good point re `R_ENVIRON_USER`, I'm working on a broader update of `auk`, so will include this.

**Comment by mstrimas** [comment]
GitHub version of the package now checks `R_ENVIRON_USER` first, then falls back on `~/.Renviron`. Most people use this to set a user-level location for eBird data not a project-level location, so I'm going to keep the behavior of this function setting variable in the user-level `.Renviron` file. I'll send this to CRAN next week.
