### ISSUE TITLE
Package crankiness over Custom EBD files

### ISSUE THREAD

**Issue by ashpeele** [CornellLabofOrnithology/auk#8]
Long-time R user, but still fairly novice programmer.  Excited about this new Auk package, specifically in helping sort through massive data dumps from our Atlas projects.  However, hit immediate snag with custom data dump text files from eBird.  

Here were data request parameters: Mar 2016-Aug 2017, Virginia data only.  

As instructed, didn't mess with text file from data dump, just fed unzipped, raw text file into R.  Used auk_clean function, then moved on to trying out the auk_unique package on 'cleaned' text file.  Got the following error codes...
`> ebd<-system.file("extdata/ebd_US-VA_201603_201709_prv_relAug-2017.txt",package="auk") %>% 
read_ebd(unique=FALSE)
>Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'an integer', got '11581.83'
In addition: Warning message:
In choose_reader(reader) :
  read.delim is slow for large EBD files, for better performance insall the readr or data.table packages.`

And...

`> ebd<-system.file("extdata/ebd_VA_cleaned.txt",package="auk") %>% 
auk_ebd()
Error in auk_ebd(.) : Problem parsing header in EBD file.`

WI BBA coordinator is also encountering similar issues with the package not liking his input txt files from Cornell.  Any suggestions on troubleshooting this issue?  Thanks a lot!

**Comment by mstrimas** [comment]
Thanks for the bug report! It would be easiest to figure out what's going on if I had the file. Is it small enough that you could share it with me?

**Comment by mstrimas** [comment]
Also, `system.file("extdata/",package="auk")` should only be used when using the example data that comes with the package. When using your own data, just use: `auk_ebd("ebd_US-VA_201603_201709_prv_relAug-2017.txt")` assuming the file is in your working directory.

**Comment by ashpeele** [comment]
Hey man, 

 

Thanks for the response.  First, the data file is huge (over a gig)!  Do you have DropBox?  I could easily share via that.  Second, my mac was doing a really weird thing with the file directory.  I couldn’t get it to recognize a path to any files, unless I stuck it in that ‘extdata’ file buried in the R library.  Tried restarting program, resetting the working directory, everything I could think of.  It’s a weird glitch that I haven’t figured out yet.  

 

Let me know about Dropbox!

 

Ashley Peele, PhD  

Virginia Breeding Bird Atlas Coordinator 

www.vabba2.org  |  ebird.org/atlasva         

www.facebook.com/vabba2  

---

Conservation Management Institute, Virginia Tech

1900 Kraft Drive, Suite 250

Blacksburg, VA 24061

(540) 231-9182 office   

(540) 231-7019 fax

ashpeele@vt.edu

**Comment by mstrimas** [comment]
This odd, I'm not able to replicate the issue, the file you sent reads just fine for me. Here's what I'd suggest:

1. Install the latest package version with: `devtools::install_github("CornellLabofOrnithology/auk")`, you may need to install `devtools` first with `install.packages("devtools")`.
2. Reading will be much faster if you have the `data.table` package installed, so run `install.packages("data.table")`.
3. Let me know how that goes.

If that doesn't work, we'll have to figure out what's going on with needing to use `system.file()`. There's definitely something weird going on there. I just ran the following without trouble:

```
library(auk)

# clean
f <- "~/Downloads/ebd_US-VA_201603_201709_prv_relAug-2017.txt"
f_out <- "~/Downloads/va-ebd_clean.txt"
va_clean <- auk_clean(f, f_out)

# read
va_ebd <- read_ebd(f_out, reader = "base", unique = FALSE, rollup = FALSE)
```

**Comment by ashpeele** [comment]
Will do!  Since WI folks are having similar problems, I was hoping this wasn't a computer-specific issue, but perhaps it is in my case.  I'll re-run everything, making sure to install the additional packages and see if I can get it to work.  Thanks for the fast help, Matt!
