### ISSUE TITLE
Bug on read_sampling ?

### ISSUE THREAD

**Issue by giacomoassandri** [CornellLabofOrnithology/auk#84]
Hi,
I used for the first time the package auk to read ebird files.
I found a problem with the function read_sampling when set to unique=TRUE.
Let's consider this checklist: https://ebird.org/checklist/S49602467
There are 37 species and 6 users. 
In the output, only one record remained (only one species) and the field sampling_event_id and users_id are filled with a string of 222 words (37x6) with the repetition of the 6 sampling_event_id and the 6  users_id.
Maybe I miss something, in this case, apologies!

**Comment by mstrimas** [comment]
I believe this is the intended behavior. `read_sampling()` is meant to be used when reading the sampling event data (the checklist-level information), while the EBD (including species information) should be read with `read_ebd()`. When using `unique = TRUE`, both functions collapse group checklists down to a single checklist and the samping event IDs and observer IDs of the constituent checklists are combined. If you don't want this behavior, you can set `unique = FALSE`. Let me know if there's still confusion and I can try to clarify.

**Comment by giacomoassandri** [comment]
Thanks, now it is clear. Apologies!
